2022-01-31 06:45:59.850 [error] <0.386.0> gen_server <0.386.0> terminated with reason: {socket_error,timeout}
2022-01-31 06:45:59.851 [error] <0.386.0> CRASH REPORT Process <0.386.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-31 06:45:59.851 [error] <0.382.0> gen_server <0.382.0> terminated with reason: {socket_error,timeout}
2022-01-31 06:45:59.853 [error] <0.381.0> Supervisor {<0.381.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.382.0>, <0.384.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52049 -> 127.0.0.1:5672">>) at <0.386.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-31 06:45:59.854 [error] <0.382.0> CRASH REPORT Process <0.382.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-31 06:45:59.854 [error] <0.381.0> Supervisor {<0.381.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.382.0>, <0.384.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52049 -> 127.0.0.1:5672">>) at <0.386.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-31 06:45:59.861 [error] <0.380.0> Supervisor {<0.380.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.381.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.382.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-31 06:45:59.861 [error] <0.380.0> Supervisor {<0.380.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.381.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.382.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-31 16:40:21.787 [error] <0.401.0> gen_server <0.401.0> terminated with reason: {socket_error,timeout}
2022-01-31 16:40:21.791 [error] <0.401.0> CRASH REPORT Process <0.401.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-31 16:40:21.846 [error] <0.396.0> Supervisor {<0.396.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.397.0>, <0.399.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52103 -> 127.0.0.1:5672">>) at <0.401.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-31 16:40:21.846 [error] <0.396.0> Supervisor {<0.396.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.397.0>, <0.399.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52103 -> 127.0.0.1:5672">>) at <0.401.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-31 16:40:21.859 [error] <0.397.0> gen_server <0.397.0> terminated with reason: {socket_error,timeout}
2022-01-31 16:40:22.011 [error] <0.397.0> CRASH REPORT Process <0.397.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-31 16:40:22.011 [error] <0.395.0> Supervisor {<0.395.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.396.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.397.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-31 16:40:22.011 [error] <0.395.0> Supervisor {<0.395.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.396.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.397.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-31 16:40:22.530 [error] <0.317.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.397.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-01-31 16:40:22.532 [error] <0.317.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.397.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-01-31 16:40:22.532 [error] <0.316.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.317.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.397.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
