2022-01-30 19:45:01.461 [error] <0.338.0> gen_server <0.338.0> terminated with reason: {socket_error,timeout}
2022-01-30 19:45:01.462 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 19:45:01.462 [error] <0.330.0> Supervisor {<0.330.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.331.0>, <0.336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51659 -> 127.0.0.1:5672">>) at <0.338.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 19:45:01.462 [error] <0.330.0> Supervisor {<0.330.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.331.0>, <0.336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51659 -> 127.0.0.1:5672">>) at <0.338.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-30 19:45:01.478 [error] <0.331.0> gen_server <0.331.0> terminated with reason: {socket_error,timeout}
2022-01-30 19:45:01.478 [error] <0.331.0> CRASH REPORT Process <0.331.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 19:45:01.478 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.331.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 19:45:01.478 [error] <0.329.0> Supervisor {<0.329.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.330.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.331.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-30 21:00:01.593 [error] <0.356.0> gen_server <0.356.0> terminated with reason: {socket_error,timeout}
2022-01-30 21:00:01.596 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 21:00:01.597 [error] <0.351.0> Supervisor {<0.351.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.352.0>, <0.354.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52000 -> 127.0.0.1:5672">>) at <0.356.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 21:00:01.598 [error] <0.351.0> Supervisor {<0.351.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.352.0>, <0.354.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52000 -> 127.0.0.1:5672">>) at <0.356.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-30 21:00:01.598 [error] <0.352.0> gen_server <0.352.0> terminated with reason: {socket_error,timeout}
2022-01-30 21:00:01.598 [error] <0.352.0> CRASH REPORT Process <0.352.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 21:00:01.598 [error] <0.350.0> Supervisor {<0.350.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.351.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.352.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 21:00:01.598 [error] <0.350.0> Supervisor {<0.350.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.351.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.352.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-30 22:34:25.090 [error] <0.371.0> gen_server <0.371.0> terminated with reason: {socket_error,timeout}
2022-01-30 22:34:25.090 [error] <0.367.0> gen_server <0.367.0> terminated with reason: {socket_error,timeout}
2022-01-30 22:34:25.091 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 22:34:25.091 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-30 22:34:25.092 [error] <0.365.0> Supervisor {<0.365.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.366.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.367.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 22:34:25.092 [error] <0.365.0> Supervisor {<0.365.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.366.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.367.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-30 22:34:25.092 [error] <0.366.0> Supervisor {<0.366.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.367.0>, <0.369.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52007 -> 127.0.0.1:5672">>) at <0.371.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-30 22:34:25.092 [error] <0.366.0> Supervisor {<0.366.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.367.0>, <0.369.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52007 -> 127.0.0.1:5672">>) at <0.371.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-31 06:45:59.850 [error] <0.386.0> gen_server <0.386.0> terminated with reason: {socket_error,timeout}
2022-01-31 06:45:59.851 [error] <0.386.0> CRASH REPORT Process <0.386.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-31 06:45:59.851 [error] <0.382.0> gen_server <0.382.0> terminated with reason: {socket_error,timeout}
